### ISSUE TITLE
Block Mods

### ISSUE THREAD

**Issue by Dslacky** [Theray070696/Tier_System_Mod#1]
Hey so i need a tier mod, but everytime i block a mod for a tier the mod does not get unlocked when u kill the mob

**Comment by Theray070696** [comment]
Please attach the config you are using.

**Comment by Dslacky** [comment]
I was Testing before i started doing the whole config

# Configuration file

misc {
    # Shows the name of an item in the tooltip.
    B:showItemNames=true
}

tiers {
    # Set this to true to enable blocking entire mods.
    B:blockMods=true

```
# Mod id's that are blocked, anything from this mod cannot be crafted or used in crafting.
S:blockedMods <
    Backpack
 >

# What mob(s) you have to kill to unlock a tier. Each line is a different tier. Separate mobs with a comma, ','. Use the name used for /summon. IE: 'Pig,Cow' would set it so you have to kill a pig and a cow to unlock that tier
S:thingsToKillForTiers <
    Pig
 >

# Number of Tiers
I:tierCount=1

# What item(s) are locked for which tier. Each line is a different tier. Separate items with a comma, ','. Separate metadata with a space, ' ', use metadata -1 to block all damage values. Use the name used for /give including the 'modname:' or 'minecraft:', IE: 'minecraft:cobblestone,minecraft:stone,minecraft:log 1' will prevent people from crafting anything that uses cobblestone, stone, or spruce wood in its recipe until that tier is unlocked
S:tierRestrictions <

 >

# If true, tiers will be shared with the entire server, aka, everybody is on the same tier
B:tiersAreServerWide=false
```

}

**Comment by Theray070696** [comment]
I'm assuming you are on 1.7.10, correct?

**Comment by Dslacky** [comment]
yes

**Comment by Theray070696** [comment]
Ok, testing this on an instance with only Backpack, Tier System, and NEI.

**Comment by Theray070696** [comment]
Hmm. it seems that this happens when there is only one mob to kill for a tier. Testing with two mobs.

**Comment by Dslacky** [comment]
okay cool also i have a few suggestions:
1) when you tier up you can set a custom message to show in chat
2) block people using items and blocks that not unlocked to them as on a server people can pass levelling up 
3) each tier you do it adds a book to tier up to that level, that way you could use the hardcore quest Book to level up

**Comment by Theray070696** [comment]
1) That's possible, I'll see about that for next public release.
2) That's done on the private/GitHub branch, see https://github.com/Theray070696/Tier_System_Mod/blob/master/src/main/java/io/github/Theray070696/tiersystem/item/ItemBlocked.java
3) I think this is doable, but it could easily be done with multiple Tier-Up's for now. I'll see about being able to configure how many tiers a Tier-Up will give you in-game.

EDIT: Just found the problem with one mob for a tier, will fix in a bit, have to go to work soon.

**Comment by Dslacky** [comment]
epic :) any luck with the testing of 2 mobs

**Comment by Theray070696** [comment]
Two mobs fixes it, it's the problem I thought it was... Will work on a fix later today.

**Comment by Dslacky** [comment]
okay cool Thankyou :)

**Comment by Dslacky** [comment]
o also just another idea when you try and craft/use an item/block that is blocked it say hey you need to kill then list the mobs but only for the next tier then when you finish say tier one it then say the mobs for tier 2 and so on

**Comment by Dslacky** [comment]
Is v5 of the mod release i see a change log but cant find a download anywhere :)

**Comment by Theray070696** [comment]
It's in private testing, but you can compile the version here on GitHub (if you know how), I'll upload it on CurseForge once I fix this bug.

**Comment by Dslacky** [comment]
okay epic cant wait :D

**Comment by Dslacky** [comment]
hey quick question if say killing a wither unlocks tier one then killing a pig unlocks tier 2 can killing a pig unlock tier 2 before killing the wither

**Comment by Theray070696** [comment]
No, the previous tier MUST be unlocked for the next tiers mobs to count.

**Comment by Dslacky** [comment]
okay cool epic
