### ISSUE TITLE
sorry to bother you

### ISSUE THREAD

**Issue by Dslacky** [Theray070696/Tier_System_Mod#2]
Could i trouble you for a quick copy with the updates as trying to build a modpack and it would help alot ty :D

**Comment by Theray070696** [comment]
Sure! I'll put it on the forum thread and CurseForge as well.

https://dl.dropboxusercontent.com/u/85222445/Tier%20System/1.7.10/1.7.10-1.0.5a/tiersystem-1.7.10-1.0.5a.jar
